### ISSUE TITLE
[FR] Support for env variables and  multi-env config

### ISSUE THREAD

**Issue by dwhoban** [mediabeastnz/craft-commerce-xero#2]
- Support the creation of a xero.php file in the config directory and multi-env configuration
- support the use of .env file for config in the settings screen to avoid project.yaml issues.

This will allow for better testing in non-prod environments when the project is live.

**Comment by mylesthedev** [comment]
Should be ready for `0.9.3`

**Comment by mylesthedev** [comment]
Hey @dwhoban i've just shipped `0.9.3` which comes with an example php file named `xero-config.php`. Copy this into your config folder and rename it to `xero.php` and define all your environment settings there.

Add project config support requires quite a big more work so it wont be shipped in this release however I might look to add it later.

**Comment by dwhoban** [comment]
Thanks @mediabeastnz; You mean ENV support right - project config already works :)
