### ISSUE TITLE
OAuth 1 and Private Applications now deprecated.

### ISSUE THREAD

**Issue by dwhoban** [mediabeastnz/craft-commerce-xero#6]
Xero has [now deprecated](https://developer.xero.com/documentation/auth-and-limits/private-applications) the API this plugin uses in favour of their OAuth2 API meaning that new integrations cannot be created.

Any plans to update to OAuth2?

**Comment by dwhoban** [comment]
Worth noting that existing integrations will stop working in Dec 2020.

**Comment by mylesthedev** [comment]
On my radar for next release @dwhoban

**Comment by dwhoban** [comment]
@mediabeastnz the [Patron](https://plugins.craftcms.com/patron?utm_campaign=Craft%2BLink%2BList&utm_medium=email&utm_source=Craft_Link_List_107) plugin might help to handle the integration point.

**Comment by auralon** [comment]
@mediabeastnz any idea when the update will be released for this?  We'd like Xero integration on the project I'm currently working on, and I'm unable to use this plugin it its current state.  Many thanks!

**Comment by alexjcollins** [comment]
+1 for being able to use this with OAuth2 – cheers!

**Comment by acantes** [comment]
+1 from me too!

**Comment by damienbuckley** [comment]
+1 - can no longer use the plugin as private applications cannot be created within Xero

**Comment by alexthekiwi** [comment]
+1 have a new site which requires a Xero integration, unable to use plugin in its current state. Any updates on new version release date?

**Comment by mylesthedev** [comment]
Update from me - I've started this and am hoping to release it January or during the holidays.

**Comment by dwhoban** [comment]
@mediabeastnz let me know how I can help.

There are some changes for commerce 3 I have implemented locally and some things in Xero that could make life easier again.

**Comment by moacode** [comment]
Hey @dwhoban, I've taken this one over from Myles and will be looking to tackle the OAuth upgrade next week after Xmas. I'm keen to check out the commerce 3 changes you've implemented so feel free to raise a pull request if you think they're worthy of going back into the plugin!

**Comment by hatzipanis** [comment]
Great to hear @thejoshsmith 🎉

**Comment by dwhoban** [comment]
@thejoshsmith will have a look, some of the issues are solved with the OAuth 2 api - particularly discounts. Would be better to put that in rather than my hacks 😂

**Comment by alexthekiwi** [comment]
@thejoshsmith just wondering if you had any updates on this?
Got a client bugging me, and don't do enough Craft work myself to know where to begin 🥲

**Comment by moacode** [comment]
Hey @alexclark-nz, I've booked in some time to work on this over the weekend (apologies for the delay). Expect an update on Sunday evening all going well!

**Comment by alexthekiwi** [comment]
@thejoshsmith You're a legend 👌 Thank you!

**Comment by moacode** [comment]
Hey @alexclark-nz, just a quick update. I've started building out the new UI that's required for OAuth 2.0 and the new multi-tenanted approach. 

There's a few database migrations I need to write and then some testing so there should be a new release end of the week.

<img width="1792" alt="Screen Shot 2021-02-01 at 12 05 22 AM" src="https://user-images.githubusercontent.com/5515179/106381997-68ce9700-6421-11eb-9be8-bdbc09fd8d6b.png">

**Comment by moacode** [comment]
Another update: 

Just about there—In the process of tidying up a few odds and ends, performing some testing and updating the documentation. The migration has been more complex than I first thought (which never happens 😅).

<img width="1792" alt="Screen Shot 2021-02-09 at 9 25 08 AM" src="https://user-images.githubusercontent.com/5515179/107277123-de3d0600-6ab8-11eb-889b-92fcc47b9f39.png">

**Comment by moacode** [comment]
OK release `1.0.0-beta.1` is now available and ready for testing.

It seems pretty stable but I need to update the docs and write some automated tests.

It would be much appreciated if someone is able to give it a test run over the next couple of days and provide me with any feedback!

<img width="1792" alt="Screen Shot 2021-02-12 at 1 27 34 AM" src="https://user-images.githubusercontent.com/5515179/107636566-b1b00680-6cd1-11eb-9a0e-ad4d8ef18775.png">

**Comment by moacode** [comment]
Release `1.0.0-beta.2` now out. Will probably release a production version today.

**Comment by moacode** [comment]
Release `1.0.0` is now out so I'll close this issue. If you spot anything not working feel free to raise a subsequent issue!

**Comment by moacode** [comment]
Just a note that I had to re-create this as a new commercial plugin so that people can continue to use the older OAuth 1.0a version as a free plugin.

New repo is here: https://github.com/thejoshsmith/commerce-xero and the new plugin is currently going through the approval process.
